CREATE DATABASE DATN;
USE DATN;

CREATE TABLE PHIEUCHIS (
    MAPHIEUCHI VARCHAR(255) PRIMARY KEY,
    NOIDUNG TEXT,
    SOTIEN DOUBLE,
    NGAYCHI DATE,
    MAKETOANVIEN VARCHAR(255),
    NGUOINHAN VARCHAR(255),
    DIACHI VARCHAR(255),
    GHICHU TEXT
);

CREATE TABLE KHOAHOCS (
    MAKHOAHOC VARCHAR(255) PRIMARY KEY,
    TENKHOAHOC VARCHAR(255),
    MALINHVUC VARCHAR(255),
    SOBUOI INT,
    HOCPHI DOUBLE,
    NOIDUNGTOMTATKHOAHOC TEXT,
    NOIDUNGKHOAHOC TEXT,
    GHICHU TEXT
);

CREATE TABLE NHANVIENKETOANS (
    MANHANVIEN VARCHAR(255) PRIMARY KEY
);

CREATE TABLE PHIEUTHUS (
    MAPHIEUTHU VARCHAR(255) PRIMARY KEY,
    NOIDUNG TEXT,
    SOTIEN DOUBLE,
    NGAYTHU DATE,
    MAKETOANVIEN VARCHAR(255),
    NGUOINOP VARCHAR(255),
    DIACHI VARCHAR(255),
    GHICHU TEXT
);

CREATE TABLE LOPHOCS (
    MALOPHOC VARCHAR(255) PRIMARY KEY,
    TENLOPHOC VARCHAR(255),
    LICHHOC VARCHAR(255),
    TINHTRANG VARCHAR(255),
    NGAYBATDAU DATE,
    NGAYKETTHUC DATE,
    THULAO DOUBLE,
    DATHANHTOAN DOUBLE,
    MAKHOAHOC VARCHAR(255),
    MAPHONGHOC VARCHAR(255),
    MAGIANGVIEN VARCHAR(255),
    GHICHU TEXT
);

CREATE TABLE GIANGVIENS (
    MAGIANGVIEN VARCHAR(255) PRIMARY KEY,
    TENGIANGVIEN VARCHAR(255),
    NGAYSINH DATE,
    GIOITINH BOOLEAN,
    SOCMND VARCHAR(255),
    SODIENTHOAI VARCHAR(255),
    EMAIL VARCHAR(255),
    DIACHI VARCHAR(255),
    COQUANCONGTAC VARCHAR(255),
    TINHTRANGCONGTAC VARCHAR(255),
    GHICHU TEXT,
    MALINHVUC VARCHAR(255),
    URLHINHDAIDIEN VARCHAR(255)
);

CREATE TABLE NHANVIENS (
    MANHANVIEN VARCHAR(255) PRIMARY KEY,
    TENNHANVIEN VARCHAR(255),
    NGAYSINH DATE,
    GIOITINH BOOLEAN,
    SOCMND VARCHAR(255),
    SODIENTHOAI VARCHAR(255),
    EMAIL VARCHAR(255),
    DIACHI VARCHAR(255),
    MACHUCVU VARCHAR(255),
    NGUOINHAPTHONGTIN VARCHAR(255),
    GHICHU TEXT,
    URIHINHDAIDIEN VARCHAR(255)
);

CREATE TABLE CONGTACVIENS (
    MANHANVIEN VARCHAR(255) PRIMARY KEY
);

CREATE TABLE TAIKHOANS (
    MATAIKHOAN VARCHAR(255) PRIMARY KEY,
    TENTAIKHOAN VARCHAR(255),
    MATKHAU VARCHAR(255),
    MANHANVIEN VARCHAR(255),
    QUYENTRUYCAP VARCHAR(255),
    GHICHU TEXT
);

CREATE TABLE CHUCVUS (
    MACHUCVU VARCHAR(255) PRIMARY KEY,
    TENCHUCVU VARCHAR(255),
    TRANGTHAI BOOLEAN
);

CREATE TABLE BAIVIETS (
    MABAIVIET VARCHAR(255) PRIMARY KEY,
    TIEUDE VARCHAR(255),
    URIHINHANHMINHHOA VARCHAR(255),
    NOIDUNGTOMTAT TEXT,
    NOIDUNG TEXT,
    NGAYDANG DATE,
    NGUOIVIETBAI VARCHAR(255),
    LANCAPNHATCUOICUNG DATE,
    SOLUONGTRUYCAP INT,
    MENU VARCHAR(255),
    TRANGTHAI BOOLEAN
);

CREATE TABLE EMAILS (
    EMAIL VARCHAR(255) PRIMARY KEY
);

CREATE TABLE HOCVIENS (
    MAHOCVIEN VARCHAR(255) PRIMARY KEY,
    TENHOCVIEN VARCHAR(255),
    NGAYSINH DATE,
    GIOITINH BOOLEAN,
    SOCMND VARCHAR(255),
    SODIENTHOAI VARCHAR(255),
    EMAIL VARCHAR(255),
    DIACHI VARCHAR(255),
    TINHTRANGHOCTAP VARCHAR(255),
    NGUOINHAPTHONGTIN VARCHAR(255),
    GHICHU TEXT,
    URIHINHDAIDIEN VARCHAR(255),
    KHOAHOCQUANTAM1 VARCHAR(255),
    KHOAHOCQUANTAM2 VARCHAR(255),
    NGAYCAPNHATGANNHAT DATE
);

CREATE TABLE LIENHES (
    MAKHACH VARCHAR(255) PRIMARY KEY,
    HOTEN VARCHAR(255),
    EMAIL VARCHAR(255),
    SODIENTHOAI VARCHAR(255),
    YKIEN TEXT,
    NGAYLIENHE DATE
);

CREATE TABLE CHITIETLOPHOCS (
    MACTLH VARCHAR(255) PRIMARY KEY,
    MAHOCVIEN VARCHAR(255),
    MALOPHOC VARCHAR(255),
    HOCPHI DOUBLE,
    MIENGIAMHOCPHI DOUBLE,
    DATHUHOCPHI BOOLEAN,
    SOTIENTHU DOUBLE,
    DIEM DOUBLE,
    NGAYCAPCHUNGCHI DATE,
    XEPLOAI VARCHAR(255),
    DIEMDANH VARCHAR(255),
    GHICHU TEXT
);

CREATE TABLE PHONGHOCS (
    MAPHONGHOC VARCHAR(255) PRIMARY KEY,
    TENPHONGHOC VARCHAR(255),
    SOCHONGOI INT,
    GHICHU TEXT
);

CREATE TABLE LINHVUCS (
    MALINHVUC VARCHAR(255) PRIMARY KEY,
    TENLINHVUC VARCHAR(255)
);

CREATE TABLE THISINHDUTHIS (
    MATHISINHDUTHI VARCHAR(255) PRIMARY KEY,
    TENTHISINHDUTHI VARCHAR(255),
    NGAYSINH DATE,
    GIOITINH BOOLEAN,
    SOCMND VARCHAR(255),
    SODIENTHOAI VARCHAR(255),
    EMAIL VARCHAR(255),
    DIACHI VARCHAR(255),
    DIENDANGKY VARCHAR(255),
    MALICHTHI VARCHAR(255),
    MAPHONGTHI VARCHAR(255),
    DIEM DOUBLE,
    XEPLOAI VARCHAR(255),
    NGAYCAPCHUNGCHI DATE,
    GHICHU TEXT,
    URLHINHDAIDIEN VARCHAR(255)
);

CREATE TABLE LICHTHIS (
    MALICHTHI VARCHAR(255) PRIMARY KEY,
    MALINHVUC VARCHAR(255),
    TENCHUNGCHI VARCHAR(255),
    NGAYTHI DATE,
    THONGTINCHITIET TEXT,
    LEPHITHI DOUBLE
);