ALTER TABLE LOPHOCS DROP FOREIGN KEY FK_LOPHOCS_GIANGVIENS;
ALTER TABLE CHITIETLOPHOCS DROP FOREIGN KEY FK_CHITIETLOPHOCS_HOCVIENS;

ALTER TABLE GIANGVIENS DROP PRIMARY KEY;
ALTER TABLE HOCVIENS DROP PRIMARY KEY;

ALTER TABLE GIANGVIENS 
ADD COLUMN MATAIKHOAN VARCHAR(255) NOT NULL UNIQUE,
ADD CONSTRAINT PK_GIANGVIENS PRIMARY KEY (MATAIKHOAN),
ADD CONSTRAINT FK_GIANGVIENS_TAIKHOANS FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOANS(MATAIKHOAN);

ALTER TABLE HOCVIENS 
ADD COLUMN MATAIKHOAN VARCHAR(255) NOT NULL UNIQUE,
ADD CONSTRAINT PK_HOCVIENS PRIMARY KEY (MATAIKHOAN),
ADD CONSTRAINT FK_HOCVIENS_TAIKHOANS FOREIGN KEY (MATAIKHOAN) REFERENCES TAIKHOANS(MATAIKHOAN);


ALTER TABLE LOPHOCS ADD CONSTRAINT FK_LOPHOCS_GIANGVIENS FOREIGN KEY (MAGIANGVIEN) REFERENCES GIANGVIENS(MATAIKHOAN);
ALTER TABLE CHITIETLOPHOCS ADD CONSTRAINT FK_CHITIETLOPHOCS_HOCVIENS FOREIGN KEY (MAHOCVIEN) REFERENCES HOCVIENS(MATAIKHOAN);
